# Generated by Django 5.1.1 on 2024-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_alter_assignmentsubmission_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("not_started", "Not Started"),
                    ("reviewed", "Reviewed"),
                ],
                default="not_started",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subtaskstatus",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("pending", "Pending")],
                max_length=50,
            ),
        ),
    ]
