# Generated by Django 5.1.1 on 2024-09-25 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="subspacemember",
            old_name="spaceMember",
            new_name="space_member",
        ),
        migrations.RemoveField(
            model_name="group",
            name="member_count",
        ),
        migrations.RemoveField(
            model_name="space",
            name="member_count",
        ),
        migrations.RemoveField(
            model_name="space",
            name="subspace_count",
        ),
        migrations.RemoveField(
            model_name="subspace",
            name="group_count",
        ),
        migrations.RemoveField(
            model_name="subspace",
            name="reviewee_count",
        ),
        migrations.RemoveField(
            model_name="subspace",
            name="reviewer_count",
        ),
        migrations.AlterField(
            model_name="space",
            name="space_bio",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="subspace",
            name="sub_space_bio",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="spacemember",
            unique_together={("space", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="subspacemember",
            unique_together={("space_member", "sub_space")},
        ),
    ]
