# Generated by Django 5.1.1 on 2024-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0002_rename_spacemember_subspacemember_space_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="spacemember",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subspace",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subspacemember",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
