# Generated by Django 5.1.1 on 2024-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0004_space_space_token_alter_group_group_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceinvitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
