# Generated by Django 5.1.1 on 2024-10-06 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0006_spacejoinrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spacejoinrequest",
            unique_together={("space", "user")},
        ),
    ]
