# Generated by Django 5.1.1 on 2024-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0007_alter_spacejoinrequest_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subspacemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("reviewer", "Reviewer"),
                    ("reviewee", "Reviewee"),
                    ("owner", "Owner"),
                ],
                default="reviewee",
                max_length=30,
            ),
        ),
    ]
