# Generated by Django 5.1.1 on 2024-09-25 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
        ("spaces", "0002_rename_spacemember_subspacemember_space_member_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentteam",
            name="submission_count",
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="iteration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="assignmentdetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubtask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentreviewee",
            unique_together={("assignment", "reviewee")},
        ),
        migrations.AlterUniqueTogether(
            name="assignmentreviewer",
            unique_together={("assignment", "reviewer")},
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "member")},
        ),
    ]
