# Generated by Django 5.1.1 on 2024-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_assignment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="assignmentdetails",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="assignmentreviewee",
            name="reviewee_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("not_submitted", "Not_Submitted"),
                    ("completed", "Completed"),
                ],
                default="not_submitted",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubtask",
            name="tag",
            field=models.CharField(
                choices=[
                    ("compulsory", "Compulsory"),
                    ("OPTIONAL", "Optional"),
                    ("brownie_point", "Brownie_Points"),
                ],
                default="OPTIONAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubtask",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="assignmentteam",
            name="team_name",
            field=models.CharField(max_length=150),
        ),
    ]
