# Generated by Django 5.1.1 on 2024-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_assignmentteam_team_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="visible_to_all",
            field=models.BooleanField(default=True),
        ),
    ]
