# Generated by Django 5.1.1 on 2024-09-23 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_bio", models.CharField(max_length=150)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="user_profile/"),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_background/"
                    ),
                ),
                ("department", models.CharField(max_length=50)),
                ("enrollment_no", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
