# Generated by Django 5.1.1 on 2024-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_bio",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
