# Generated by Django 5.1.1 on 2024-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userprofile_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="enrollment_no",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
