# Generated by Django 5.1.1 on 2024-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_userprofile_enrollment_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="enrollment_no",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
