# Generated by Django 5.1.1 on 2024-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userprofile_enrollment_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
