# Generated by Django 5.1.1 on 2024-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userprofile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="enrollment_no",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
